file_format: "1"
id: soflee
name: Soflee
type: shield
url: https://github.com/josefadamcik/SofleKeyboard
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - encoder
  - underglow
  - studio
siblings:
  - soflee_left
  - soflee_right
