manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/urob
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      revision: v0.2 # set to desired version 
      import: app/west.yml
    - name: zmk-auto-layer
      remote: urob
      revision: v0.2 # set to same version
  self:
    path: config
